"""Premium PDF Generator for BPRC Medical Records.

Generates comprehensive PDF reports including nursing and doctor assessments.
"""
import io
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.lib.units import mm
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from datetime import datetime

def render_placeholder_pdf(title: str, subtitle: str, body_lines: list[str]) -> bytes:
    """Legacy placeholder - kept for compatibility"""
    buf = io.BytesIO()
    c = canvas.Canvas(buf, pagesize=A4)
    w, h = A4

    # Header bar
    c.setFont("Helvetica-Bold", 16)
    c.drawString(20*mm, h-25*mm, "BPRC")
    c.setFont("Helvetica", 10)
    c.drawRightString(w-20*mm, h-22*mm, "SayMed – Pain Edition")
    c.setLineWidth(0.8)
    c.line(20*mm, h-28*mm, w-20*mm, h-28*mm)

    # Title
    c.setFont("Helvetica-Bold", 14)
    c.drawString(20*mm, h-40*mm, title)
    c.setFont("Helvetica", 10)
    c.drawString(20*mm, h-47*mm, subtitle)

    # Body
    y = h-60*mm
    c.setFont("Helvetica", 11)
    for line in body_lines:
        c.drawString(20*mm, y, line[:110])
        y -= 7*mm
        if y < 25*mm:
            c.showPage()
            y = h-25*mm

    # Footer
    c.setFont("Helvetica", 8)
    c.drawString(20*mm, 15*mm, f"Generated by SayMed – Pain Edition v0.1 | {datetime.now().isoformat(timespec='seconds')}")
    c.save()
    return buf.getvalue()


def render_medical_record_pdf(encounter_data: dict, patient_data: dict, nursing_data: dict | None, medical_data: dict | None) -> bytes:
    """
    Render comprehensive medical record PDF with nursing and doctor assessments.
    """
    buf = io.BytesIO()
    c = canvas.Canvas(buf, pagesize=A4)
    w, h = A4
    margin = 20*mm
    content_width = w - 2*margin
    
    # State tracking for Y position
    current_y = h - 40*mm
    
    def draw_header():
        nonlocal current_y
        c.setFont("Helvetica-Bold", 18)
        c.drawString(margin, h-20*mm, "BANDUNG PAIN REHAB CENTER")
        c.setFont("Helvetica", 10)
        c.drawString(margin, h-27*mm, "Medical Record - Pain Assessment Form")
        c.setLineWidth(1)
        c.line(margin, h-30*mm, w-margin, h-30*mm)
        current_y = h - 40*mm
    
    def check_page_break(needed_height_mm):
        nonlocal current_y
        if current_y < (20*mm + needed_height_mm*mm):
            c.showPage()
            draw_header()
            return True
        return False

    def draw_section_title(title):
        nonlocal current_y
        check_page_break(15)
        c.setFont("Helvetica-Bold", 12)
        c.drawString(margin, current_y, title)
        c.setLineWidth(0.5)
        c.line(margin, current_y-2*mm, w-margin, current_y-2*mm)
        current_y -= 8*mm
    
    def draw_field(label, value, indent=0, bold_label=True, multi_line=True):
        nonlocal current_y
        if not value: return
        
        c.setFont("Helvetica-Bold" if bold_label else "Helvetica", 9)
        label_str = f"{label}:" if label else ""
        
        # Calculate height needed
        c.setFont("Helvetica", 9)
        val_str = str(value)
        
        # Simple text wrapping
        max_char = int((content_width/mm - indent - (40 if label else 0)) * 2.1) # approx char per line
        if max_char < 20: max_char = 20
        
        lines = []
        if multi_line:
            words = val_str.split(' ')
            current_line = []
            current_len = 0
            for word in words:
                if current_len + len(word) + 1 > max_char:
                    lines.append(" ".join(current_line))
                    current_line = [word]
                    current_len = len(word)
                else:
                    current_line.append(word)
                    current_len += len(word) + 1
            if current_line: lines.append(" ".join(current_line))
        else:
            lines = [val_str]
            
        needed = len(lines) * 5
        check_page_break(needed)
        
        c.setFont("Helvetica-Bold" if bold_label else "Helvetica", 9)
        if label:
            c.drawString((margin/mm + indent)*mm, current_y, label_str)
            text_x = (margin/mm + indent + 40)*mm
        else:
            text_x = (margin/mm + indent)*mm

        c.setFont("Helvetica", 9)
        for i, line in enumerate(lines):
            c.drawString(text_x, current_y - i*5*mm, line)
            
        current_y -= (len(lines)*5*mm + 2*mm)

    def draw_kv_row(label, value):
        draw_field(label, value, indent=0)

    # Initial Header
    draw_header()
    
    # === PATIENT INFO ===
    draw_section_title("PATIENT INFORMATION")
    draw_kv_row("Name", patient_data.get("full_name", "-"))
    draw_kv_row("RM Number", patient_data.get("rm_number", "-"))
    draw_kv_row("Date of Birth", f"{patient_data.get('dob', '-')} ({patient_data.get('age_years', '-')} y.o)")
    draw_kv_row("Sex", patient_data.get("sex", "-"))
    draw_kv_row("Address", patient_data.get("address", "-"))
    draw_kv_row("Visit Date", encounter_data.get("visit_datetime", "-"))
    current_y -= 5*mm

    # === NURSING ===
    if nursing_data:
        draw_section_title("A. NURSING ASSESSMENT")
        draw_kv_row("Chief Complaint", nursing_data.get("chief_complaint_nurse"))
        draw_kv_row("Allergies", f"{nursing_data.get('allergy_status')} {nursing_data.get('allergy_details') or ''}")
        
        draw_field("Vital Signs", 
                   f"BP: {nursing_data.get('vitals_bp_systolic')}/{nursing_data.get('vitals_bp_diastolic')} mmHg | "
                   f"HR: {nursing_data.get('vitals_hr')} bpm | RR: {nursing_data.get('vitals_rr')} | "
                   f"Temp: {nursing_data.get('vitals_temp_c')} C | SpO2: {nursing_data.get('vitals_spo2')}%")
        
        if nursing_data.get("weight_kg"):
            draw_field("Anthropometry",
                       f"Weight: {nursing_data.get('weight_kg')} kg | Height: {nursing_data.get('height_cm')} cm | BMI: {nursing_data.get('bmi')}")

        draw_field("Pain Assessment",
                   f"Score: {nursing_data.get('pain_score')}/10 | Loc: {nursing_data.get('pain_location')} | "
                   f"Dur: {nursing_data.get('pain_duration')} | Scale: {nursing_data.get('pain_scale_type')}")
        
        draw_field("Screening", 
                   f"Fall Risk: {nursing_data.get('fallrisk_level')} | Nutrition: {nursing_data.get('nutrition_risk_label')}")
        current_y -= 5*mm

    # === MEDICAL ===
    if medical_data:
        draw_section_title("B. MEDICAL ASSESSMENT (DOCTOR)")
        
        # Anamnesis
        draw_field("Chief Complaint", medical_data.get("chief_complaint_doctor"))
        draw_field("Anamnesis", medical_data.get("anamnesis") or "-")
        draw_field("History", 
                   f"Prev Dx/Tx: {medical_data.get('previous_diagnoses_treatments') or '-'}\n"
                   f"RPD: {medical_data.get('rpd') or '-'}\n"
                   f"RPK: {medical_data.get('rpk') or '-'}\n"
                   f"Allergies: {medical_data.get('allergy_history') or '-'}")
        
        draw_field("Current Meds", medical_data.get("current_medications"))

        # Physical Exam (JSON parsing)
        pe = medical_data.get("physical_exam_json")
        if pe:
            draw_section_title("C. PHYSICAL EXAMINATION")
            
            # General / MSK
            if pe.get("pemeriksaan_fisik"):
                pf = pe["pemeriksaan_fisik"]
                draw_field("Cranial Nerves", pf.get("cranial_nerve"))
                draw_field("Romberg/Tandem", pf.get("romberg_tandem"))
                if pf.get("pain_detect"):
                    pd = pf["pain_detect"]
                    draw_field("Pain Detect", f"Score: {pd.get('score')} ({pd.get('interpretasi')}) | {pd.get('sensory_descriptors')}")

            if pe.get("muskuloskeletal"):
                msk = pe["muskuloskeletal"]
                msk_txt = ", ".join([f"{k.title()}: {v}" for k, v in msk.items() if v])
                draw_field("Musculoskeletal", msk_txt)

            # Neuro Grid Summary
            if pe.get("neurologis") and pe["neurologis"].get("rows"):
                rows = pe["neurologis"]["rows"]
                # Filter useful rows
                abnormal = []
                for k, v in rows.items():
                    mot = v.get("motorik","")
                    sen = v.get("sensorik","")
                    if (mot and mot.lower() not in ["dbn","5","5/5","normal"]) or (sen and sen.lower() not in ["dbn","normal","+"]):
                         abnormal.append(f"{k}: M={mot} S={sen}")
                
                if abnormal:
                    draw_field("Neurology Abn", "; ".join(abnormal))
                else:
                    draw_field("Neurology", "General neurological status within normal limits (C1-S4 motor/sensor/reflexes)")

        # Diagnosis & Plan
        draw_section_title("D. DIAGNOSIS & PLAN")
        draw_field("Working Dx", medical_data.get("working_diagnosis"))
        draw_field("Differential Dx", medical_data.get("differential_diagnosis"))
        draw_field("Plan / Therapy", medical_data.get("plan_notes"))
        
        if medical_data.get("lab_results"): draw_field("Labs", medical_data.get("lab_results"))
        if medical_data.get("radiology"): draw_field("Radiology", medical_data.get("radiology"))
        
        draw_field("Follow Up", f"{medical_data.get('followup_date') or '-'} {medical_data.get('followup_time') or ''}")

    # Footer
    c.setFont("Helvetica", 8)
    c.drawString(margin, 15*mm, f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')} | SayMed Pain Edition")
    
    c.save()
    return buf.getvalue()
